apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - auth-server-database-deployment.yml
  - auth-server-deployment.yml
  - auth-server-service.yml
  - ingress.yml
  - config-file.yml
  - secret-config-file.yml
  - mysl_service.yml
  - namespace.yml
  - persistentVolume.yml
images:
  - name: abhishekkargetti/authserviceimages
    newName: abhishekkargetti/authserviceimages
    newTag: v1.0.0
  - name: abhishekkargeti/authserviceimages
    newTag: v1.0.2
